---
- name: Set up Active Directory and DNS on Windows Server 2016
  hosts: windows
  gather_facts: yes
  tasks:

    - name: Install Active Directory Domain Services role
      win_feature:
        name: AD-Domain-Services
        state: present

    - name: Install DNS role
      win_feature:
        name: DNS
        state: present

    - name: Promote server to Domain Controller
      win_shell: |
        Import-Module ADDSDeployment
        Install-ADDSDomainController -DomainName "pointbreak.test" `
        -DomainNetbiosName "PointBreak" `
        -SafeModeAdministratorPassword (ConvertTo-SecureString "YourPasswordHere" -AsPlainText -Force) `
        -InstallDNS:$true `
        -NoGlobalCatalog:$false `
        -Force:$true
      register: dc_promote_output

    - name: Wait for reboot after domain promotion
      wait_for:
        port: 3389
        host: "{{ inventory_hostname }}"
        state: started
        delay: 10
        timeout: 600
      when: dc_promote_output.rc == 0

    - name: Add user "Bodhi" to Active Directory
      win_user:
        name: Bodhi
        password: "P@55w0rd"
        state: present
        groups: "Domain Users"

    - name: Configure DNS settings for the domain
      win_dns_record:
        name: "california"
        zone: "pointbreak.test"
        type: A
        value: "{{ ansible_host }}"
        state: present

    - name: Verify DNS resolution with nslookup (local)
      win_command: nslookup california.pointbreak.test
      register: nslookup_output
      failed_when: "'california' not in nslookup_output.stdout"

    - name: Test DNS lookup (external)
      win_command: nslookup google.com
      register: external_nslookup
