- name: Automate OpenVPN Backend Setup
  hosts: openvpn
  become: yes
  vars:
    admin_password: "AdminSoftMania@123"
  tasks:
    - name: Copy script to remote server
      copy:
        src: openvpn_setup.sh
        dest: /tmp/openvpn_setup.sh
        mode: '0755'

    - name: Execute OpenVPN setup script
      command: /tmp/openvpn_setup.sh
